#!/bin/zsh

# Install
zsh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

# Set to default, since the --unattended flag causes the installation to skip that step
# skip this step if on GitHub runner, since chsh is not possible there (requires password input)
if [ -z "$CI" ]; then
  chsh -s $(which zsh)
fi

# Add zsh-syntax-highlighting plugin
rm -rf $HOME/.oh-my-zsh/custom/plugins/example*
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# Add theme
rm $HOME/.oh-my-zsh/custom/themes/example*
ln -s ~/.devenv/themes/oceanic-voivode.zsh-theme ~/.oh-my-zsh/custom/themes/oceanic-voivode.zsh-theme

# Reload the new .zshrc so that some commands can be properly run and more executables are added to path
zsh
