#!/bin/zsh

# Install
zsh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Set to default, since the --unattended flag causes the installation to skip that step
chsh -s $(which zsh)

# Add theme
rm $HOME/.oh-my-zsh/custom/themes/example*
cp $HOME/Repos/DevEnv/themes/dracula_prime.zsh-theme $HOME/.oh-my-zsh/custom/themes

# Add aliases
copyConfigsToHome .zsh_aliases

# Write theme to zshrc
# sed -i -Ee 's/(^ZSH_THEME=("?))[a-zA-Z0-9_ -]*("?$)/\1dracula_prime\2/g' $HOME/.zshrc
perl -i -pe's/(^ZSH_THEME=("?))[a-zA-Z0-9_ -]*("?$)/$1tdracula_prime$2/g' $HOME/.zshrc

# Ensure extended configurations are loaded
echo '. ~./zshrc.ext' >> $HOME/.zshrc
