name: Test Installation
on: [push]
jobs:
  oh-my-zsh-installation:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: zsh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      - run: zsh -c 'echo "$ZSH, $SHELL'
