name: Test Installation
on: [push]
jobs:
  oh-my-zsh-installation:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: $HOME/Repos/DevEnv
      - run: echo $HOME
      - run: ls -lah $HOME; ls -lah $HOME/Repos; ls -lah "$HOME/Repos/"
